//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamingStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductosVentaDT
    {
        public int Producto { get; set; }
        public int VentaDT { get; set; }
    
        public virtual Productos Productos { get; set; }
        public virtual VentasDT VentasDT { get; set; }
    }
}
